apiVersion: v1
kind: Service
metadata:
  labels:
    app: observability
  name: observability
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 4000
  selector:
    app: observability
  type: ClusterIP
