version: "3"
services:
  db:
    restart: always
    image: postgres
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pgdata:
    driver: local
