# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: observability_app
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["docker.for.mac.localhost:4000"]
