apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: konga
  name: konga
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - image: pantsel/konga
        name: konga
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: konga
  name: konga
  namespace: kong
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: konga
