apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      nodeSelector:
#        hardened: "true"
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
        ports:
        - containerPort: 80
